### ISSUE TITLE
After installing and creating an OpenAI secret, I get an error decoding response body

### ISSUE THREAD

**Issue by jimadamskye** [xhjkl/well#4]
well what is the most convoluted function across this codebase\?

>> what is the most convoluted function across this codebase?

⠙Error: error decoding response body

While the README should have mentioned that you actually needed to got a secret key, there should also be documentation for testing things. Another issue mentioned a verbose option. That would also help in situations like this.

**Comment by xhjkl** [comment]
Hi, @jimadamskye! Thank you for the suggestion, and for trying the thing out!

There is a good change the issue will be resolved in the next release, so stay updated.

**Comment by xhjkl** [comment]
Let's keep #3 as the tracking issue for both of these issues. Cheers!
