### ISSUE TITLE
crash in Chinese characters

### ISSUE THREAD

**Issue by jiahut** [xhjkl/well#7]
When the program encounters Chinese characters, it crashes and exits immediately. Below is the log from when the program exits, and any Chinese characters can reproduce this
issue.
```
thread 'main' panicked at /home/zhijia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/well-0.0.2/src/io.rs:36:44:
called `Result::unwrap()` on an `Err` value: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by xhjkl** [comment]
Please see the latest update:
```
$ cargo install well
```

Would love to know how it goes.

**Comment by xhjkl** [comment]
@jiahut, assuming it's resolved. Feel free to reopen otherwise.
